Feat/render tagged models
gmyrianthous/dbt-airflow pull request #123
Opened 2023-12-04 09:13 UTC by DimitriSam

**Overview:**
This PR introduces a new feature in the package that allows for the execution of dbt models based on specified tags. It aims to provide more flexibility and control over model execution in Airflow workflows.

**Changes Made:**

- `Added filter_tags property`: A new property named filter_tags has been added to DbtAirflowConfig. This property accepts a list of tags.
- `Node filtering mechanism`: The functionality filters out nodes from the dbt manifest that are tagged with any of the specified tags in filter_tags.
- `Dependency update`: After filtering nodes the dependencies are updated.

2023-12-04 09:46 UTC, gmyrianthous requested changes

2023-12-04 11:19 UTC, DimitriSam commented on dbt_airflow/parser/dbt.py
> +    def load(cls, data: Dict[str, Any], **kwargs) -> "Manifest":
I did this in case we want to apply additional functionalities, such as exclude_tags or filter_by_paths etc

2023-12-04 11:21 UTC, DimitriSam commented on dbt_airflow/parser/dbt.py
> +            node_name: node for node_name, node in data["nodes"].items()
In the 1st step we filter only tagged models. Then, in the 2nd step we iterate again the initial dictionary and we keep only tests that depend on the selected nodes of the 1st step

2023-12-05 16:22 UTC, gmyrianthous commented on dbt_airflow/parser/dbt.py
> +    def include_by_tags(data, tags: List[str]) -> Dict[str, Any]:
Missing type annotation for `data`

2023-12-05 16:26 UTC, gmyrianthous commented on dbt_airflow/parser/dbt.py
> +    def exclude_by_tags(data, exclude_tags: List[str]) -> Dict[str, Any]:
Missing type annotation for `data`

2023-12-05 16:26 UTC, gmyrianthous commented on dbt_airflow/parser/dbt.py
> +    def filter_tests_with_dependencies(all_nodes, filtered_nodes):
Missing annotations

2023-12-05 16:26 UTC, gmyrianthous commented on dbt_airflow/parser/dbt.py
> +    def update_dependencies(filtered_nodes):
Same here

2023-12-05 17:13 UTC, gmyrianthous approved these changes

2023-12-05 17:15 UTC, merged